name: Build and Push Quarkus App
on:
  push:
    branches:
      - main # Adjust to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

   
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    - name: Build Quarkus app
      run: ./mvnw clean package -DskipTests

    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: pratheebapc/project-management:latest # Customize with your Docker Hub details
